Fix AsyncTypes to service load from the correct classloader instead of using the current thread context classloader
This is because you cannot guarantee the implementation is going to be available to the thread.
For instance, in the WildFly case, the implementation classes are not available in the deployment's classloader.
This manifests as:

Cannot deploy ftAsynchronous.war: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ftAsynchronous.war\".WeldStartService" => "Failed to start service
    Caused by: org.jboss.weld.exceptions.DefinitionException: Exception List with 1 exceptions:
Exception 0 :
org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceDefinitionException: Invalid @Asynchronous on org.eclipse.microprofile.fault.tolerance.tck.asynchronous.AsyncClassLevelClient.serviceCS(java.util.concurrent.Future): must return java.util.concurrent.Future or